### ISSUE TITLE
ŞşĞğİ character support

### ISSUE THREAD

**Issue by muhlisatac** [alexeiva/philosopher#5]
Hi!
Can you please add "Ş ş Ğ ğ İ" character support. We want to use your font familiy. I was looking it from [this](https://fonts.google.com/specimen/Philosopher?preview.text=%C5%9E%C5%9F%C4%9E%C4%9F%C4%B0&preview.text_type=custom#standard-styles) link.
Best regards.

**Comment by alexeiva** [comment]
Just checked — they are included in the font

<img width="240" alt="Screenshot 2024-06-07 at 11 38 41" src="https://github.com/alexeiva/philosopher/assets/16634089/f9f140e9-47eb-4cb4-9a43-8ae7f3b9e90e">


<img width="721" alt="Screenshot 2024-06-07 at 11 37 50" src="https://github.com/alexeiva/philosopher/assets/16634089/a91220a5-e787-4a1f-a635-5c7304393049">
